print("Hello".lower())
print("hello".upper())
print("hello world".capitalize())
print("  hello world is food".strip())
print("Hello".startswith("he"))
print("helo".endswith("o"))
print("hello,hi".replace("hi","Naveen"))
print("hi my name, is ,naveen".split(","))
x="god".join(["a","b","c"])
print(x)
print(type(x))
print("hello this is naveen".find("is"))
print("hello this is naveen".index("naveen"))
print("hello world".count("or"))
print("12345".isnumeric())
